### ISSUE TITLE
Can't load video data for frame 4

### ISSUE THREAD

**Issue by zhaomeihu** [emredog/humaneva#1]
I downloaded the HumanEva_II dataset and ran  ComputeError2DExample.m. I found that the size of this.data.Markers in cur_frame.m was (6,193,3) which made it can't load video data for frame 4. 
`if (nargin > 1)
    this.current_position = this.stream_offset + (frame_id - 1) * this.stream_scaling;
end`
`if (ceil(this.current_position) > size(this.data.Markers,1))
    pose  = [];
    valid = 0;
    return;
end`
Is there anything wrong? What's the meaning of the shape (6,193,3)? Thank you~
@emredog

**Comment by emredog** [comment]
Sorry, currently I have no means of debugging this code.

Unless you're not using Matlab 2014b on Ubuntu 14, I strongly recommend to start with the original code: http://humaneva.is.tue.mpg.de/datasets_human_1
